### ISSUE TITLE
Prepare for pyls 0.17

### ISSUE THREAD

**Issue by lgeiger** [lgeiger/ide-python#96]
`python-language-server@0.17` will come with new plugins, a configurable installation process and more config options for existing plugins: https://github.com/palantir/python-language-server/compare/0.16.0...develop

## TODO
- [ ] Update Readme
  - [ ] Update installation docs
  - [ ] Add links to the new plugins
- [ ] Update error messages according to new install process
- [ ] Add support for the new configuration options and test if they are passed correctly to `pyls`

Contributions on this issue are very welcome 🎉
